### ISSUE TITLE
Next steps - 2019/11/28

### ISSUE THREAD

**Issue by RobBlumberg** [UBC-MDS/DSCI_532_GROUP_109#27]
Tasks for next few days:

- George make second plot (survivor by deck) and add to make_plot script
- George create "deck legend"
- Rob document titanic_viz notebook, and document make_plot script
- Rob deploy on heroku

Last thing to do:
- Post individual reflections in a new issue, Trevor will consolidate/summarize

**Comment by trevorkwan** [comment]
great idea, remember to send us the link to the app on heroku Rob!

**Comment by gptzjs** [comment]
Looks good, will have this all done in the next hour
