### ISSUE TITLE
(1) Removal of gridlines and axes on boat plot (2) Attribution of photo

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_532_GROUP_109#28]
We were going to remove the gridlines and the axes on the boat plot right? Since these don't convey any information to the user. Will also make the viz cleaner looking.

Also, we should attribute the source of the photo which is a free image from [thoughtco.com](url)

**Comment by RobBlumberg** [comment]
I will definitely remove gridlines and axis coords
