### ISSUE TITLE
Dropdown instructions

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_532_GROUP_109#38]
As discussed in the lab yesterday, we should put text to the right or above the dropdown window (above is better I think) instructing users to choose the deck (similar to image below)

![image](https://user-images.githubusercontent.com/4149251/69859035-2a9b7d80-1248-11ea-86e3-c7d786ae0dc7.png)

Some options:

- "Select deck"
- "Choose a deck to display" *

Not sure if this is absolutely necessary, but we could also place a note somewhere stating that each deck contains cabins of all three classes as this is not obvious at first glance. A good place would be on the same line as the dropdown but right justified to the frame.

Some options:

- "Each deck has passenger cabins of all classes" *
- "Passenger cabins of all classes are on each deck

_* My preference_

**Comment by RobBlumberg** [comment]
I agree, we should add "Choose a deck to display" and I like your note "Each deck has passenger cabins of all classes" 
I can make both changes now
