### ISSUE TITLE
Task division - Friday Nov 29th

### ISSUE THREAD

**Issue by RobBlumberg** [UBC-MDS/DSCI_532_GROUP_109#45]
Next set of tasks we need to complete (ideally tonight) are:

- Add an introduction to our app (historical intro and segue into our viz): I can add a placeholder in the app where the text will go, George write up the text? I will launch the app on Heroku when this is done to see how it looks there.
- Edit the proposal so that the scope of our research question is more focused, ie., dont mention exploration of other variables in our dashboard since our viz's aren't demonstrating this. Trevor, can you do this? 
- Add division of tasks in our contract and how we plan to delegate - George? 
- 

Let me know if you guys are okay with this sub-task delegation. Also, anything else I'm missing?

**Comment by gptzjs** [comment]
1. I will place the intro text into app.py

2. I will edit the contact to explicitly address some degree of division of roles and responsibilities, although we all agree that for a project of this size, we do not need to and do not want to draw hard lines

3. I thought we already outlined "the procedure by which new tasks are introduced and assigned" but I shall do so more explicitly

**Comment by RobBlumberg** [comment]
Great, sounds good. I inserted the placeholder text and submitted a PR - George, go ahead and add the text

**Comment by gptzjs** [comment]
Done
