### ISSUE TITLE
Repo folders and subdirectories

### ISSUE THREAD

**Issue by RobBlumberg** [UBC-MDS/DSCI_532_GROUP_109#5]
We should organize our files in a few main subdirectories: 
- img: images
- data: data files
- doc: documentation and any .md files directly relating to the project itself (Other docs like license, contract/code of conduct should probably just be left in root)
- src: python/R scripts and jupyter notebooks

**Comment by gptzjs** [comment]
Agreed. So I will push the Code of Conduct (.md file) to the root.

**Comment by RobBlumberg** [comment]
I was thinking that it makes sense to organize our src folder into python_scripts and jupyter_notebooks, thoughts on this?
