### ISSUE TITLE
Ended editing app.py with no changes

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_532_GROUP_109#54]
Created app2.py to save my edits for team review:

1. Centered the jumbotron image and introduction
2. Edited the introduction, removed colon from dropdown title and edited deck/class note
2. Realigned text with plot borders
3. Changed some font sizes and colours for better visibility and contrast

The boat plot is not rendering on my browser, but how can that be? Rob, since you are able to see it, are there any changes you made to make_plot.py which may not have been pushed? That's the only reason I can think of why it works for you but not me.

**Comment by RobBlumberg** [comment]
Let me know if it renders after accepting my PR. I will look at the formatting changes now
