### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by carlinakim** [UBC-MDS/DSCI_532_GROUP_109#66]
Here is some feedback for your dash! 

- move the dropdown to the right side so it is easier for the user to find 
- size of the titanic photo could be smaller
- add a note stating that the cabin location was from Class 1
- change the default deck level 
- change the grey colour in the bar plots 
- add note stating you can hover over the points for passenger information

**Comment by RobBlumberg** [comment]
Thank you Carlina,
Great feedback! We have made notes and will be implementing some of your suggestions, stay tuned
