### ISSUE TITLE
milestone discussion

### ISSUE THREAD

**Issue by taohuang-ubc** [UBC-MDS/DSCI_532_GROUP_109#67]
The only button we can change is the deck level.

The two charts are not interactive. 

There should be also class separation shown in the plot.

People can walk to a location that is not near their cabin.

Change in the  description's 'location'  to 'deck level'.

**Comment by RobBlumberg** [comment]
Thank you Tao,
Great feedback! We have made notes and will be implementing some of your suggestions, stay tuned
