### ISSUE TITLE
Feedback from Lab

### ISSUE THREAD

**Issue by slbsolomon** [UBC-MDS/DSCI_532_GROUP_109#68]
Great job! Our favourite part was the tooltips - it was also a small introduction to genders and survival rates, which would be an expansion.
Here are our comments of areas for improvement:
- We initially started clicking on the deck levels before we saw the dropdown. James and I both quite liked seeing the deck slices, but it was unclear that it wasn't clickable. Some options may be to either make the deck levels clickable or move the dropdown higher up.
- We were unsure what the empty cabins meant - adding a comment about that would be helpful!
- For the bottom 2 graphs, if you wanted to divide the data differently, you could maybe facet survival rate of decks by class, or maybe connect the bottom right graph to the deck selection callback to highlight the deck we are currently looking at? I would call this a low priority "nice to have" update.
- Lots of excess space - I immediately adjusted my browser, but James missed that note.

**Comment by RobBlumberg** [comment]
Thank you Sam, 
Great feedback! We have made notes and will be implementing some of your suggestions, stay tuned
