### ISSUE TITLE
TA comments on milestone 2

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI_532_GROUP_109#73]
Hello,

Thank you for your submission of milestone 2. I am sure that you put a lot of effort into producing the app and its documentation. I see that you are always commiting and using pull requests, but try to add an extended description of the commits that you find a little vague. You also use issues for communication and task assignment, but I see that team members tend not to comment on issues.

Regarding the app, I like how you use a mix of bar charts, the ship plots for visualizations. I have some suggestions for the app that I will be listing below.
- It is always required for an online visualization tool to have a description of the app at the beginning (user's guide). 
- I tried the app on Firefox first and it didn't work (I couldn't see the charts), but it worked perfectly on Chrome. Is there something you can do?
- You should include or cite the data source.
- You have used some interactive features which I find very helpful for users.
- Finally, I like your reflection you did every thing that was required in this task

**Comment by RobBlumberg** [comment]
Thanks Mohammed, comments will be addressed in R repo, so closing this issue
