### ISSUE TITLE
changes to app based on TA feedback

### ISSUE THREAD

**Issue by RobBlumberg** [UBC-MDS/DSCI_532_GROUP_109#75]
Summarizing some changes we will make to the app on the back of the TA feedback:

1 - adding sources for data
2 - adding music
3 - adding app description

Will tackle points 1 and 2 now, still waiting to hear from you goerge about clarification regarding point 3

**Comment by RobBlumberg** [comment]
Also, was just thinking - are we going to relaunch our python app on heroku so that the TAs can see the changes?

**Comment by RobBlumberg** [comment]
I've added the source links, thoughts on this
<img width="1323" alt="Screen Shot 2019-12-06 at 5 27 33 PM" src="https://user-images.githubusercontent.com/55078244/70366647-bd8e7600-184d-11ea-8a92-8a38eb304fc7.png">

**Comment by gptzjs** [comment]
Closing issue as discussed
